### ISSUE TITLE
CrvAeth - no monetary value displayed

### ISSUE THREAD

**Issue by RnbWd** [tomprsn/Yearnings#1]
No monetary value is displayed for crvAeth

**Comment by jstashh** [comment]
@RnbWd Could you update to the latest version through Testflight and let me know if this has been fixed please?

**Comment by RnbWd** [comment]
thanks for the update! Yes, the monetary value is displayed now, but the value is 4% higher than what's shown by zapper.fi

**Comment by jstashh** [comment]
@RnbWd I'm just using the oracle here https://etherscan.io/address/0xd3ca98D986Be88b72Ff95fc2eC976a5E6339150d
Not sure what zapper are using. One of us is right 🤷‍♂️
